{pkgs}: {
  deps = [
    pkgs.ffmpeg
    pkgs.chromaprint
    pkgs.zlib
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.pkg-config
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.freetype
    pkgs.cairo
    pkgs.ffmpeg-full
    pkgs.portaudio
    pkgs.lsof
    pkgs.avahi
    pkgs.shairport-sync
    pkgs.iana-etc
  ];
}
